### ISSUE TITLE
OSM Wiki pages missing & Organised Editing Activities missing

### ISSUE THREAD

**Issue by rory** [osmlab/appledata#152]
The [Organised Editing Guidelines](https://wiki.osmfoundation.org/wiki/Organised_Editing_Guidelines) are a great tool to help people like you make useful and productive edits. Can you please link to your OSM Wiki page for all these projects? And add to the [Organised Editing Activities list](https://wiki.openstreetmap.org/wiki/Organised_Editing/Activities) We're all want the same thing, a high quality OSM map, and documentation 

This applies to many of these projects, including: #126 #127 #128 #129 #130 #131 #132 #133 #134 #135 #136 #137 #138 #139 #140 #141 #142 #144 #145 #146 #147 #148 #149 #150

**Comment by chazanov** [comment]
@rory Who has allowed you tho change your user name to something absolutely incomprehensible like https://www.openstreetmap.org/user/%e1%9a%9b%e1%9a%8f%e1%9a%92%e1%9a%90%e1%9a%94%e1%9a%8f%e1%9a%94%e1%9a%8b%e1%9a%9c%20%f0%9f%8f%b3%ef%b8%8f%e2%80%8d%f0%9f%8c%88 ? Are there any rules regarding the homo flag?

**Comment by iandees** [comment]
@chazanov Language like "homo flag" is not welcome on this GitHub organization. Please be aware of how your language affects others and modify your comment so that it is on topic and not hateful.

**Comment by awisemanapple** [comment]
Hi Rory, that's a good suggestion, I am working on that now.

**Comment by rory** [comment]
Thanks for [adding to the list](https://wiki.openstreetmap.org/w/index.php?title=Organised_Editing/Activities&diff=1890505&oldid=1890236), but you should also add a wiki page for this activity. Just listing to Github isn't the best. We all agree the OSM Wiki is the best place for a permanent, canonical documenation, which I'm sure you want.

_(thanks for cleaning up the comments too)_

**Comment by mfrasca** [comment]
a quick search for "Data Improvements in" issues, I count 131 projects, all ongoing. IMO: all these issues are more like projects, than issues in the sense given to the term in the software industry.

@rory , do you suggest that the @appleosm team should keep the overview in a OSM wiki page, and hold a page for each issue here?  that would imply a lot of repetition of information, which can't be desirable, and I also think that OSM does not have the power to enforce this request.  

I for one would be satisfied with more active involvement of the local communities when there's sparks of activity on each of these projects.  like what Andrew promised for Panamá in [this comment](https://github.com/osmlab/appledata/issues/37#issuecomment-593710581).  I don't know what prevented Andrew from keeping the promise and I don't know how Apple behaves in other countries.  I sort of follow [Morocco](https://github.com/osmlab/appledata/issues/152), where I also have the impression that communication isn't public enough c.q. doesn't rely on OSM services.

**Comment by awisemanapple** [comment]
Hi Mario, thanks for the comment. We have a list of all of our projects on the OSM Wiki on our Organized Editing page here, which was posted in 2019 per the conversation above, and I have kept it updated since: 
https://wiki.openstreetmap.org/wiki/Organised_Editing/Activities/Apple. That page includes links to the individual country GitHub issues here like you suggested. That OSM wiki page and our main Github page are also linked from the general Organized Editing page https://wiki.openstreetmap.org/wiki/Organised_Editing/Activities under Apple, and the Apple OSM wiki page in the Map Data Contributions section https://wiki.openstreetmap.org/wiki/Apple#Map_data_contributions and we also link to the OSM Wiki Apple page from each GitHub issue.
